#!/bin/bash
## This script takes a list of URLs pointing to adblocker filters, hostsfiles, and domain lists.
## It then converts them into hostsfiles, and merges them together.
##
## Copyright (C) from 2018 by Miles B Huff
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.

#set -x

## If invalid input, print help.
if [[ ! -f "$1" ]]; then
	echo 'Please provide the path to a file consisting of URLs on separate lines.'
	echo 'Each URL must link to a valid adblocker blocklist.'
	echo 'You can comment out URLs by prefixing them with a hashtag.'
	echo 'You can specify URLs to hostsfiles, as well;  simply prefix them with an @ sign.'
	echo 'Domain lists can also be used -- just prefix their URLs with an ampersand.'
	echo
	echo 'gen-hosts is Copyright (C) from 2018 by Miles B Huff per GPL3.'
	echo 'This program comes with ABSOLUTELY NO WARRANTY.'
	echo 'This is free software, and you are welcome to redistribute it under certain conditions.'
	exit 1
fi

## Prepare the workspace
ROOT_PATH=$(cd $(dirname $0) && pwd);
ADBLOCKDIR='adblock'
HOSTSDIR='hosts'
DOMAINSDIR='domains'
HDIR='hackertarget'
INDIR='input'
OUTDIR='output'

WHITELIST=$(cat $ROOT_PATH/whitelist.txt | sed -e 's/#.*$//' -e '/^\s*$/d' |tr "\n" "|")
#BLACKLIST=$(cat $ROOT_PATH/blacklists/*.txt | sed -e 's/#.*$//' -e '/^\s*$/d' |tr "\n" "|")

rm -rf "$ROOT_PATH/$OUTDIR" 2> /dev/null
mkdir -p "$ROOT_PATH/$OUTDIR"
rm -rf "$ROOT_PATH/$INDIR"  2> /dev/null
mkdir -p "$ROOT_PATH/$INDIR"

#rm -rf {$ADBLOCKDIR,$HOSTSDIR,$DOMAINSDIR,$HDIR}  2> /dev/null
mkdir -p $INDIR/{$ADBLOCKDIR,$HOSTSDIR,$DOMAINSDIR,$HDIR}  2> /dev/null
mkdir -p $OUTDIR/{$ADBLOCKDIR,$HOSTSDIR,$DOMAINSDIR,$HDIR}  2> /dev/null

rm -f hosts      2> /dev/null
rm -f wget.log   2> /dev/null

## Download blocklists from specified file
echo ':: Downloading blocklists...'
echo
while read L; do

	## Skip blank lines and comments
	if [[ "$L" && $(echo "$L" | egrep -v '^#') ]]; then

		## Figure out where to download to.  Non-adblock files go right to the outdir.
		if [[ $(echo "$L" | egrep '^[@|&|!]') ]]; then
			if [[  $(echo "$L" | egrep '^[@]') ]]; then
				cd "$INDIR/$HOSTSDIR"
			fi
			if [[  $(echo "$L" | egrep '^[&]') ]]; then
				cd "$INDIR/$DOMAINSDIR"
			fi
			if [[  $(echo "$L" | egrep '^[!]') ]]; then
				cd "$INDIR/$HDIR"
			fi
		else
			cd "$INDIR/$ADBLOCKDIR"
		fi

		## Download the file
		wget -nv $(echo "$L" | sed 's/^[@|&|!]//') 2>&1 | tee wget.log
		FILE=$(cat wget.log | sed 's/.*-> "//' | sed 's/".*//')
		rm -f wget.log

		## Cleanup
		cd $ROOT_PATH
		unset FILE
	fi
done < "$1"
echo

## Convert blocklists into hostsfiles
echo ':: Creating hostsfiles...'
#### adblock ####
for F in $(ls -1 "$INDIR/$ADBLOCKDIR"); do
	echo "$F"
	./easylist.pl "$INDIR/$ADBLOCKDIR/$F" > "$OUTDIR/$ADBLOCKDIR/$F"
#	./hostsblock "$INDIR/$ADBLOCKDIR/$F" > "$OUTDIR/$ADBLOCKDIR/$F"
done
echo

#### hosts ####
for F in $(ls -1 "$ROOT_PATH/$INDIR/$HOSTSDIR"); do
     cat $ROOT_PATH/$INDIR/$HOSTSDIR/$F |sed 's/\r/\n/g'|grep -v -E '^#|^$' |grep -E '0.0.0.0|127.0.0.1' |awk '{print $2}' > "$ROOT_PATH/$OUTDIR/$HOSTSDIR/$F"
done

#### domains ####
for F in $(ls -1 "$ROOT_PATH/$INDIR/$DOMAINSDIR"); do
     cat $ROOT_PATH/$INDIR/$DOMAINSDIR/$F |sed 's/\r/\n/g' | grep -v -E 'Malvertising list by Disconnect|^Blocklist of hostnames and domains|^$|^#' | sed -e 's/<.*>//g'  > "$ROOT_PATH/$OUTDIR/$DOMAINSDIR/$F"
done

#### hackertarget ####
for F in $(ls -1 "$ROOT_PATH/$INDIR/$HDIR"); do
     cat $ROOT_PATH/$INDIR/$HDIR/$F |sed 's/\r/\n/g' | cut -d "," -f 1  > "$ROOT_PATH/$OUTDIR/$HDIR/$F"
done




### Merge hostsfiles
echo ':: Merging hostsfiles...'
for F in $(ls -1 "$OUTDIR/$ADBLOCKDIR"); do
	echo "$F"
	cat "$OUTDIR/$ADBLOCKDIR/$F" >> $OUTDIR/blacklist
done
for F in $(ls -1 "$OUTDIR/$HOSTSDIR"); do
	echo "$F"
	cat "$OUTDIR/$HOSTSDIR/$F" >>  $OUTDIR/blacklist
done
for F in $(ls -1 "$OUTDIR/$DOMAINSDIR"); do
	echo "$F"
	cat "$OUTDIR/$DOMAINSDIR/$F" >> $OUTDIR/blacklist
done
for F in $(ls -1 "$OUTDIR/$HDIR"); do
	echo "$F"
	cat "$OUTDIR/$HDIR/$F" >> $OUTDIR/blacklist
done

for F in $(ls -1 $ROOT_PATH/blacklists/*.txt); do
	echo "$F"
	cat "$F" >> $OUTDIR/blacklist
done

echo

## Clean up hostsfile
echo ':: Cleanup...'
cat $OUTDIR/blacklist | sed 's/^.*#.*$//' | sed 's/127\.0\.0\.1//'  | sed 's/0\.0\.0\.0//' | sed 's/\t/ /' | sed 's/  / /' | sed 's/\r//' | sort -u | uniq |  grep -v -E '^$|localhost|^0.0.0.0|^\.' |grep -v -E "$WHITELIST"  > $ROOT_PATH/hosts
#rm -f hosts
#echo '# Generated by gen-hosts (https://github.com/MilesBHuff/gen-hosts)' > hosts
#cat "$OUTDIR/balcklist" >> hosts
echo

cat $ROOT_PATH/hosts |awk '{print "server:\nlocal-data: \""$1" A 0.0.0.0\""}' > ads_hole.conf

## Done
#rm -rf "$ADBLOCKDIR" "$OUTDIR"
echo ':: Done.'
echo 'Your new hostsfile can be found at ./hosts'
echo


